#!/bin/sh

ssh ubuntu@13.113.148.171 <<EOF
    cd ~/node-app
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g forever
    forever start ecosystem.config.js
    forever list
    exit
EOF
